### ISSUE TITLE
change_scene infinite loop of errors

### ISSUE THREAD

**Issue by stellaw1** [stellaw1/fellow-crossing#10]
![image](https://user-images.githubusercontent.com/46392676/87613354-f0d99300-c6c1-11ea-8fd3-0da30de849c3.png)

## Problem:
this error pops up repeatedly when clicking on the coffee room or cinema, which is supposed to trigger a change scene(from World.tscn to CoffeeRoom.tscn or Cinema.tscn). The error causes an infinite loop on the client side and causes the game to crash. I cant seem to trace what part of the code causes it. If anyone has any insight or has people they are able to ask, that would be much appreciated

## Possible solutions:
 - work the room into World.tscn instead of changing to a different scene

## Resources:
 - https://docs.godotengine.org/en/latest/tutorials/networking/high_level_multiplayer.html?highlight=set_network_mode
 - https://docs.godotengine.org/en/stable/tutorials/misc/change_scenes_manually.html

**Comment by kanav99** [comment]
I think this is due to my code, right now the networking code assumes that all the players are in same scene and just syncs the position. It doesn't takes into account the scene where it is in. We have two paths from here

1. Either just do everything in the main scene i.e. World.tscn, dont change scene at all
2. Or sync everyone's scene too which they are in. I would not recommend this solution because, syncing the position was too hard, I don't know how much more time we would need to invest in this

**Comment by stellaw1** [comment]
Definitely agree with solution #1. I will start working room layouts into World.tscn tomorrow morning then!
